# Never copy this file from other mods, always use https://github.com/ALIENQuake/ProjectInfinity/wiki/Adding-metadata-for-mod

# ini section header is required to avoid false detection
[Metadata]

# Full name of the mod, without the list of supported games, without the version number, without 'Mod'
Name = Dialogue Choice Additions

# Author name or nick, don't use an email address
Author = VioletSister

# Short description of the mod, main goals, features etc
Description = Adds new dialogue choices to some dialogues in Baldur's Gate.

# Web address of mod readme file, comma-separated list
Readme = https://github.com/VioletSister/DialogueChoiceAdditions/blob/main/README.MD

# Web address of mod dedicated forum or forum thread 
# Forum = https://www.example.com/forums/categories/forum-thread

# Web address of mod personal Homepage, no need to duplicate with a mod dedicated forum
Homepage = https://github.com/VioletSister/DialogueChoiceAdditions

# If you use GitHub.com, simply use https://github.com/AccountOrOrgName/RepositoryName (omit /releases)
# read more about Delta Updates https://github.com/ALIENQuake/ProjectInfinity/wiki/Delta-Updates-for-mods-hosted-at-Github
Download = https://github.com/VioletSister/DialogueChoiceAdditions

# Type of LABELs used by the mod, read more here https://www.gibberlings3.net/forums/topic/32516-tutorial-what-is-label
LabelType = GloballyUnique

# Dynamic Install Order, use mod ID as tp2 name without file extension and `setup-` prefix

# This mod must be installed *before* those ModID listed below, comma-separated list:
Before = EET_end

# This mod must be installed *after* those ModID listed below, comma-separated list:
# DCA does not need to come after VVA, as DCA does not change NPC dialogue lines (but adds a few
# NPC lines that are shortened from vanilla lines)
# The DCA VVA compatibility patch can technically be used without VVA,
# but the tp2 prevents it to avoid accidental installation without VVA
After = EEFIXPACK, EET, JasteySodTweaks-MoreDialogueChoices_PreventDeadEnds